version: '3'
services:
    api:
        build:
            context: .
            dockerfile: ./docker/dev/Dockerfile
        image: filament-api
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${API_PORT:-81}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        volumes:
            - '.:/var/www/html'
        depends_on:
            - db
        networks:
            - filament-api-network
    db:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 0
        volumes:
            - 'filament-mysql:/var/lib/mysql'
        networks:
            - filament-api-network
networks:
    filament-api-network:
        driver: bridge
volumes:
    filament-mysql:
        driver: "local"
